######################################################################
# Automatically generated by qmake (3.0) Mon May 19 14:03:21 2014
######################################################################

QT += core gui
QT += widgets


TEMPLATE = app
TARGET = Calculator
INCLUDEPATH += .

# Input
HEADERS += button.h calculator.h
SOURCES += button.cpp calculator.cpp main.cpp
